# Databázové p?ipojení (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/EShopBackend
spring.datasource.username=postgres
spring.datasource.password=820414Got
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate nastavení
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Správa databázového schématu
# Proto?e v pom.xml máte Flyway, je ideální nechat tvorbu tabulek na n?m:
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

debug=true